#!/bin/sh
export CLONE_ADDFLAG="-b $DOCKER_TAG"
echo "Previus set $CLONE_ADDFLAG"
if [ "$DOCKER_TAG" = "latest" ]; then
    export CLONE_ADDFLAG="-b master"
fi
echo "Now Loading $CLONE_ADDFLAG"
docker build -t $IMAGE_NAME .
